apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system
spec:
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: sales
          image: sales-image
          ports:
            - name: sales
              containerPort: 3000
            - name: sales-debug
              containerPort: 3010
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
 
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system
spec:
  selector:
    app: sales
